name: Create Translation Branches and PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'handbook_v*_en' 

jobs:
  create_translation_branches:
    if: contains(github.head_ref, 'en') && contains(github.base_ref, 'main') 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'ntluong95'
          git config --global user.email 'ph.ntluong95@gmail.com'

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | gh auth login --with-token

      - name: Create language branches and PRs
        run: |
          LANGS=("fr" "es" "vn" "jp" "tr" "pt" "ru")  
          PR_BRANCH="${{ github.head_ref }}"  
          VERSION_SUFFIX="${PR_BRANCH#handbook_}"
          PREFIX="${BASE_BRANCH%_en}"
          for lang in "${LANGS[@]}"; do
            NEW_BRANCH="handbook_${VERSION_SUFFIX/_en/_$lang}"
            # Check if the branch already exists
            if ! git rev-parse --verify --quiet "${NEW_BRANCH}"; then
              git checkout -b "${NEW_BRANCH}"
            else
              git checkout "${NEW_BRANCH}" 
            git pull origin "${NEW_BRANCH}" 
            git push origin "${NEW_BRANCH}"
            gh pr create --base $BASE_BRANCH --head $NEW_BRANCH --title "Update $lang handbook" --body "Automated pull request for $lang handbook version ${VERSION_SUFFIX/_en/}"
          done


