name: Render Book on PR to Main

on:
  push:
    branches:
      - main

jobs:
  build-and-render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false
          # uncomment and specify version if needed
          # version: SPECIFIC-QUARTO-VERSION-HERE

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::googlesheets4
            any::learnr
            any::swirl
            any::here
            any::rio
            any::openxlsx
            any::pacman
            any::renv
            any::remotes
            any::linelist
            any::naniar
            any::janitor
            any::gtsummary
            any::rstatix
            any::broom
            any::lmtest
            any::easystats
            any::epicontacts
            any::EpiNow2
            any::EpiEstim
            any::projections
            any::incidence2
            any::i2extras
            any::epitrix
            any::distcrete
            any::cowplot
            any::RColorBrewer
            any::ggnewscale
            any::DiagrammeR
            any::gghighlight
            any::ggrepel
            any::plotly
            any::gganimate
            any::sf
            any::tmap
            any::OpenStreetMap
            any::spdep
            any::rmarkdown
            any::reportfactory
            any::officer
            any::flexdashboard
            any::shiny
            any::knitr
            any::flextable
            any::ggtree
            any::ape
            any::treeio
            any::babelquarto
            any::babeldown
              

      - name: Render Book
        run: Rscript -e 'source("quarto_runfile").R'

      - name: Publish to Netlify (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      
